"""Embedded playground UI route."""
from fastapi import APIRouter, Request
from fastapi.responses import (
    HTMLResponse,
    PlainTextResponse,
    RedirectResponse,
    Response,
)

from app.ui.templates import render_home

router = APIRouter(include_in_schema=False)

SITE_URL = "https://rapidapi-metadata-extractor.onrender.com"
LOGO_URL = "https://rapidapi-metadata-extractor.onrender.com/assets/logo.png"

ROBOTS_TXT = f"""User-agent: *
Allow: /

Sitemap: {SITE_URL}/sitemap.xml
"""

SITEMAP_XML = f"""<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>{SITE_URL}/</loc>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>
"""


@router.get("/", response_class=HTMLResponse)
def home_ui(request: Request):
    # CSP nonce is generated by app.security.response_headers' middleware
    # (request.state, set before this handler runs) so the header and the
    # markup it authorizes always match.
    nonce = getattr(request.state, "csp_nonce", "")
    return render_home(nonce)


@router.get("/robots.txt", response_class=PlainTextResponse)
def robots_txt():
    return ROBOTS_TXT


@router.get("/sitemap.xml")
def sitemap_xml():
    return Response(content=SITEMAP_XML, media_type="application/xml")


@router.get("/favicon.ico")
def favicon():
    # Browsers request this path directly regardless of the <link rel="icon">
    # tag in <head>; redirect rather than proxy so we don't need a static-file
    # mount for one asset that's already public on GitHub.
    return RedirectResponse(url=LOGO_URL, status_code=308)
