"""Embedded playground UI route."""
from fastapi import APIRouter, Request
from fastapi.responses import (
    HTMLResponse,
    PlainTextResponse,
    RedirectResponse,
    Response,
)

from app.extraction.pipeline import fetch_and_extract_raw
from app.ui.templates import render_home

router = APIRouter(include_in_schema=False)

SITE_URL = "https://rapidapi-metadata-extractor.onrender.com"
LOGO_URL = "https://rapidapi-metadata-extractor.onrender.com/assets/logo.png"
DEFAULT_DEMO_URL = "https://buffer.com"

ROBOTS_TXT = f"""User-agent: *
Allow: /

Sitemap: {SITE_URL}/sitemap.xml
"""

SITEMAP_XML = f"""<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>{SITE_URL}/</loc>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>
"""


@router.get("/", response_class=HTMLResponse)
async def home_ui(request: Request):
    # CSP nonce is generated by app.security.response_headers' middleware
    # (request.state, set before this handler runs) so the header and the
    # markup it authorizes always match.
    nonce = getattr(request.state, "csp_nonce", "")

    # Pre-render the default demo result server-side (same pipeline call
    # /demo/extract makes, called in-process rather than over HTTP) so the
    # page has real, crawlable content on first paint instead of only after
    # the client-side fetch in analyzeUrl() resolves — see templates.py's
    # render_home docstring. Any failure (target site down, etc.) falls back
    # to the previous empty-placeholder behavior rather than breaking the
    # page; the client script still fetches a fresh live result on load
    # either way.
    try:
        demo_data = await fetch_and_extract_raw(DEFAULT_DEMO_URL, None)
    except Exception:
        demo_data = None

    return render_home(nonce, demo_data)


@router.get("/robots.txt", response_class=PlainTextResponse)
def robots_txt():
    return ROBOTS_TXT


@router.get("/sitemap.xml")
def sitemap_xml():
    return Response(content=SITEMAP_XML, media_type="application/xml")


@router.get("/favicon.ico")
def favicon():
    # Browsers request this path directly regardless of the <link rel="icon">
    # tag in <head>; redirect rather than proxy so we don't need a static-file
    # mount for one asset that's already public on GitHub.
    return RedirectResponse(url=LOGO_URL, status_code=308)
